language: generic
dist: xenial
sudo: false
before_install:
- gem install bundler
- composer self-update
install:
- bundle install
before_script:
- bundle exec hatchet ci:setup
# Heroku CLI's .deb installs to /usr/bin/heroku
# Travis CI _also installs Heroku CLI_ in its base image to /usr/local/bin/heroku
# On Travis CI, /usr/local/bin comes _before_ /usr/bin in the $PATH.
# So even though we are installing the latest via hatchet, the Travis CI heroku
# is winning out due to the /usr/local/bin coming first in the PATH.
# Create a shim in /home/travis/bin (which comes before /usr/local/bin and /usr/bin)
# to get the Heroku CLI installed from hatchet first in the PATH
- ln -s /usr/bin/heroku /home/travis/bin/heroku
- which heroku
- heroku -v
script: bundle exec parallel_rspec -n 7 --group-by runtime --unknown-runtime 1 --runtime-log "test/var/log/parallel_runtime_rspec.${STACK}.log" --verbose-process-command --combine-stderr --prefix-output-with-test-env-number test/spec/
after_script:
- bundle exec hatchet destroy --all
- cat parallel_runtime_rspec.log | grep -E '^test/spec/[a-z0-9_/\.-]+\.rb:[0-9]+\.[0-9]+$' | sort
env:
  global:
  - HATCHET_RETRIES=3
  - IS_RUNNING_ON_CI=true
  - HATCHET_APP_LIMIT=200
  - HATCHET_EXPENSIVE_MODE=1
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-php"
  - HATCHET_APP_PREFIX="htcht-${TRAVIS_JOB_ID}-"
matrix:
    include:
      - env: STACK=cedar-14
        if: branch = main OR tag IS present
      - env: STACK=heroku-16
        if: branch = main OR tag IS present
      - env: STACK=heroku-18
        if: branch = main OR tag IS present
      - env: STACK=cedar-14 HEROKU_PHP_PLATFORM_REPOSITORIES="- https://lang-php.s3.amazonaws.com/dist-cedar-14-develop/"
        if: branch != main AND tag IS blank
      - env: STACK=heroku-16 HEROKU_PHP_PLATFORM_REPOSITORIES="- https://lang-php.s3.amazonaws.com/dist-heroku-16-develop/"
        if: branch != main AND tag IS blank
      - env: STACK=heroku-18 HEROKU_PHP_PLATFORM_REPOSITORIES="- https://lang-php.s3.amazonaws.com/dist-heroku-18-develop/"
        if: branch != main AND tag IS blank
